import { useState } from "react";
import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { Sparkles, Save } from "lucide-react";
import { toast } from "sonner";
import { PageHeader } from "@/components/pqi/PageHeader";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { AREAS, EQUIPMENT } from "@/lib/mock-data";

export const Route = createFileRoute("/deviations/new")({
  head: () => ({
    meta: [
      { title: "Create Deviation | Pharma Quality Intelligence" },
      {
        name: "description",
        content:
          "Capture manufacturing event details to begin an AI-assisted deviation investigation.",
      },
      { property: "og:title", content: "Create Deviation" },
      {
        property: "og:description",
        content: "Capture the event details to begin an investigation.",
      },
    ],
  }),
  component: CreateDeviation,
});

function Field({
  label,
  children,
  htmlFor,
}: {
  label: string;
  children: React.ReactNode;
  htmlFor?: string;
}) {
  return (
    <div className="space-y-2">
      <Label htmlFor={htmlFor}>{label}</Label>
      {children}
    </div>
  );
}

function CreateDeviation() {
  const navigate = useNavigate();
  const [form, setForm] = useState({
    id: "DEV-1026",
    description:
      "Temperature exceeded the specified operating range of 20–25°C for 18 minutes during batch B12345 processing.",
    area: "Manufacturing Area 3",
    equipment: "Reactor R-102",
    batch: "B12345",
    datetime: "2026-08-26T10:42",
    reporter: "John Smith",
    classification: "Temperature Excursion",
    severity: "High",
    comments: "",
  });

  const set = (key: keyof typeof form, value: string) =>
    setForm((f) => ({ ...f, [key]: value }));

  return (
    <div className="space-y-6 pb-10">
      <PageHeader
        title="Create Deviation"
        subtitle="Capture the event details to begin an investigation."
      />

      <div className="surface-card p-6">
        <div className="grid gap-5 md:grid-cols-2">
          <Field label="Deviation ID" htmlFor="dev-id">
            <Input id="dev-id" value={form.id} readOnly className="font-mono" />
            <p className="text-xs text-muted-foreground">
              Auto-generated by the quality system.
            </p>
          </Field>

          <Field label="Initial Classification">
            <Select
              value={form.classification}
              onValueChange={(v) => set("classification", v)}
            >
              <SelectTrigger>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {[
                  "Temperature Excursion",
                  "Process Parameter Deviation",
                  "Equipment Failure",
                  "Documentation Deviation",
                  "Environmental Excursion",
                  "Cleaning Deviation",
                ].map((c) => (
                  <SelectItem key={c} value={c}>
                    {c}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </Field>

          <div className="md:col-span-2">
            <Field label="Deviation Description" htmlFor="dev-desc">
              <Textarea
                id="dev-desc"
                rows={3}
                value={form.description}
                onChange={(e) => set("description", e.target.value)}
              />
            </Field>
          </div>

          <Field label="Area">
            <Select value={form.area} onValueChange={(v) => set("area", v)}>
              <SelectTrigger>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {AREAS.map((a) => (
                  <SelectItem key={a} value={a}>
                    {a}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </Field>

          <Field label="Equipment">
            <Select value={form.equipment} onValueChange={(v) => set("equipment", v)}>
              <SelectTrigger>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {EQUIPMENT.map((e) => (
                  <SelectItem key={e} value={e}>
                    {e}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </Field>

          <Field label="Batch Number" htmlFor="batch">
            <Input
              id="batch"
              className="font-mono"
              value={form.batch}
              onChange={(e) => set("batch", e.target.value)}
            />
          </Field>

          <Field label="Date and Time" htmlFor="datetime">
            <Input
              id="datetime"
              type="datetime-local"
              value={form.datetime}
              onChange={(e) => set("datetime", e.target.value)}
            />
          </Field>

          <Field label="Reporter" htmlFor="reporter">
            <Input
              id="reporter"
              value={form.reporter}
              onChange={(e) => set("reporter", e.target.value)}
            />
          </Field>

          <Field label="Severity">
            <Select value={form.severity} onValueChange={(v) => set("severity", v)}>
              <SelectTrigger>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {["Low", "Medium", "High", "Critical"].map((s) => (
                  <SelectItem key={s} value={s}>
                    {s}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </Field>

          <div className="md:col-span-2">
            <Field label="Additional Comments" htmlFor="comments">
              <Textarea
                id="comments"
                rows={5}
                placeholder="Immediate actions taken, observations, related records…"
                value={form.comments}
                onChange={(e) => set("comments", e.target.value)}
              />
            </Field>
          </div>
        </div>

        <div className="mt-7 flex flex-wrap justify-end gap-2 border-t border-border pt-5">
          <Button
            variant="outline"
            onClick={() => toast.success(`${form.id} saved as draft`)}
          >
            <Save className="size-4" />
            Save as Draft
          </Button>
          <Button
            size="lg"
            onClick={() =>
              navigate({
                to: "/investigations/$investigationId",
                params: { investigationId: "INV-2026-1026" },
              })
            }
          >
            <Sparkles className="size-4" />
            Analyze with AI
          </Button>
        </div>
      </div>
    </div>
  );
}
