/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ChangeControlsIndexRouteImport } from './routes/change-controls/index'
import { Route as ChangeControlsChangeIdRouteImport } from './routes/change-controls/$changeId'
import { Route as ChangeControlsNewRouteImport } from './routes/change-controls/new'
import { Route as DeviationsIndexRouteImport } from './routes/deviations/index'
import { Route as DeviationsDeviationIdRouteImport } from './routes/deviations/$deviationId'
import { Route as DeviationsNewRouteImport } from './routes/deviations/new'
import { Route as InvestigationsIndexRouteImport } from './routes/investigations/index'
import { Route as InvestigationsInvestigationIdRouteImport } from './routes/investigations/$investigationId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangeControlsIndexRoute = ChangeControlsIndexRouteImport.update({
  id: '/change-controls/',
  path: '/change-controls/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangeControlsChangeIdRoute = ChangeControlsChangeIdRouteImport.update({
  id: '/change-controls/$changeId',
  path: '/change-controls/$changeId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangeControlsNewRoute = ChangeControlsNewRouteImport.update({
  id: '/change-controls/new',
  path: '/change-controls/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviationsIndexRoute = DeviationsIndexRouteImport.update({
  id: '/deviations/',
  path: '/deviations/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviationsDeviationIdRoute = DeviationsDeviationIdRouteImport.update({
  id: '/deviations/$deviationId',
  path: '/deviations/$deviationId',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviationsNewRoute = DeviationsNewRouteImport.update({
  id: '/deviations/new',
  path: '/deviations/new',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigationsIndexRoute = InvestigationsIndexRouteImport.update({
  id: '/investigations/',
  path: '/investigations/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigationsInvestigationIdRoute =
  InvestigationsInvestigationIdRouteImport.update({
    id: '/investigations/$investigationId',
    path: '/investigations/$investigationId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/insights': typeof InsightsRoute
  '/settings': typeof SettingsRoute
  '/change-controls/$changeId': typeof ChangeControlsChangeIdRoute
  '/change-controls/new': typeof ChangeControlsNewRoute
  '/deviations/$deviationId': typeof DeviationsDeviationIdRoute
  '/deviations/new': typeof DeviationsNewRoute
  '/investigations/$investigationId': typeof InvestigationsInvestigationIdRoute
  '/change-controls/': typeof ChangeControlsIndexRoute
  '/deviations/': typeof DeviationsIndexRoute
  '/investigations/': typeof InvestigationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/insights': typeof InsightsRoute
  '/settings': typeof SettingsRoute
  '/change-controls/$changeId': typeof ChangeControlsChangeIdRoute
  '/change-controls/new': typeof ChangeControlsNewRoute
  '/deviations/$deviationId': typeof DeviationsDeviationIdRoute
  '/deviations/new': typeof DeviationsNewRoute
  '/investigations/$investigationId': typeof InvestigationsInvestigationIdRoute
  '/change-controls': typeof ChangeControlsIndexRoute
  '/deviations': typeof DeviationsIndexRoute
  '/investigations': typeof InvestigationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/insights': typeof InsightsRoute
  '/settings': typeof SettingsRoute
  '/change-controls/$changeId': typeof ChangeControlsChangeIdRoute
  '/change-controls/new': typeof ChangeControlsNewRoute
  '/deviations/$deviationId': typeof DeviationsDeviationIdRoute
  '/deviations/new': typeof DeviationsNewRoute
  '/investigations/$investigationId': typeof InvestigationsInvestigationIdRoute
  '/change-controls/': typeof ChangeControlsIndexRoute
  '/deviations/': typeof DeviationsIndexRoute
  '/investigations/': typeof InvestigationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/insights'
    | '/settings'
    | '/change-controls/$changeId'
    | '/change-controls/new'
    | '/deviations/$deviationId'
    | '/deviations/new'
    | '/investigations/$investigationId'
    | '/change-controls/'
    | '/deviations/'
    | '/investigations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/insights'
    | '/settings'
    | '/change-controls/$changeId'
    | '/change-controls/new'
    | '/deviations/$deviationId'
    | '/deviations/new'
    | '/investigations/$investigationId'
    | '/change-controls'
    | '/deviations'
    | '/investigations'
  id:
    | '__root__'
    | '/'
    | '/insights'
    | '/settings'
    | '/change-controls/$changeId'
    | '/change-controls/new'
    | '/deviations/$deviationId'
    | '/deviations/new'
    | '/investigations/$investigationId'
    | '/change-controls/'
    | '/deviations/'
    | '/investigations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InsightsRoute: typeof InsightsRoute
  SettingsRoute: typeof SettingsRoute
  ChangeControlsChangeIdRoute: typeof ChangeControlsChangeIdRoute
  ChangeControlsNewRoute: typeof ChangeControlsNewRoute
  DeviationsDeviationIdRoute: typeof DeviationsDeviationIdRoute
  DeviationsNewRoute: typeof DeviationsNewRoute
  InvestigationsInvestigationIdRoute: typeof InvestigationsInvestigationIdRoute
  ChangeControlsIndexRoute: typeof ChangeControlsIndexRoute
  DeviationsIndexRoute: typeof DeviationsIndexRoute
  InvestigationsIndexRoute: typeof InvestigationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-controls/': {
      id: '/change-controls/'
      path: '/change-controls'
      fullPath: '/change-controls/'
      preLoaderRoute: typeof ChangeControlsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-controls/$changeId': {
      id: '/change-controls/$changeId'
      path: '/change-controls/$changeId'
      fullPath: '/change-controls/$changeId'
      preLoaderRoute: typeof ChangeControlsChangeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-controls/new': {
      id: '/change-controls/new'
      path: '/change-controls/new'
      fullPath: '/change-controls/new'
      preLoaderRoute: typeof ChangeControlsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deviations/': {
      id: '/deviations/'
      path: '/deviations'
      fullPath: '/deviations/'
      preLoaderRoute: typeof DeviationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deviations/$deviationId': {
      id: '/deviations/$deviationId'
      path: '/deviations/$deviationId'
      fullPath: '/deviations/$deviationId'
      preLoaderRoute: typeof DeviationsDeviationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deviations/new': {
      id: '/deviations/new'
      path: '/deviations/new'
      fullPath: '/deviations/new'
      preLoaderRoute: typeof DeviationsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigations/': {
      id: '/investigations/'
      path: '/investigations'
      fullPath: '/investigations/'
      preLoaderRoute: typeof InvestigationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigations/$investigationId': {
      id: '/investigations/$investigationId'
      path: '/investigations/$investigationId'
      fullPath: '/investigations/$investigationId'
      preLoaderRoute: typeof InvestigationsInvestigationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InsightsRoute: InsightsRoute,
  SettingsRoute: SettingsRoute,
  ChangeControlsChangeIdRoute: ChangeControlsChangeIdRoute,
  ChangeControlsNewRoute: ChangeControlsNewRoute,
  DeviationsDeviationIdRoute: DeviationsDeviationIdRoute,
  DeviationsNewRoute: DeviationsNewRoute,
  InvestigationsInvestigationIdRoute: InvestigationsInvestigationIdRoute,
  ChangeControlsIndexRoute: ChangeControlsIndexRoute,
  DeviationsIndexRoute: DeviationsIndexRoute,
  InvestigationsIndexRoute: InvestigationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
